#! /usr/bin/python3
# -*- coding: UTF-8 -*-

from site import addsitedir
addsitedir('/usr/local/share/asmaa/modules')
addsitedir('/usr/share/asmaa/modules')
addsitedir('./modules')
addsitedir('modules')

import asm_main
asm_main.main()
